force-app/main/default/objects/Absence__c/fields/Approval__c.field-meta.xml
<CustomField>
    <fullName>Approval__c</fullName>
    <label>Approval</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AbsenceManager__c/AbsenceManager__c.object-meta.xml
<CustomObject>
    <label>Absence Manager</label>
    <nameField>
        <label>Absence Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Absences Manager</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AbsenceController_Test.cls
@isTest
public class AbsenceController_Test {

     @testSetup static void setup() {
     
		Profile profile_admin=[SELECT Id, Name FROM Profile where Name ='System Administrator' limit 1][0];
		User u = new user();
		
        u.Alias = 'admin';
        u.LastName = 'LastName 123abc';
		u.Email = 'abc@testmail.com';
		u.Username = 'xyz@mailtest.com';
		u.CommunityNickname = 'BT123';
		u.LocaleSidKey = 'en_US';
		u.TimeZoneSidKey = 'GMT';
		u.ProfileID = profile_admin.Id;
		u.LanguageLocaleKey = 'en_US';
		u.EmailEncodingKey = 'UTF-8';
		
         insert u;
         System.runAs(u) {
         Employee__c	  e  = new Employee__c( Name='test emp', User__c=u.Id);
             insert e;
      	 AbsenceManager__c abm = new AbsenceManager__c(Name='test AbsenceManager',Employee__c=e.Id);
              insert abm;
         Absence__c        ab=new Absence__c(AbsenceManager__c=abm.Id,Approval__c='Pending');
              insert ab;
             
         }
    }
    
       static testMethod void test_Items_AbsenceManagerWrapper(){
		treedata.Items itm=new treedata.Items();
    		itm.name = 'test item name';
			itm.label ='test item label';
			itm.expanded=true;
			itm.disabled=true;
		treedata.AbsenceManagerWrapper amw=new treedata.AbsenceManagerWrapper();
            amw.name='test AbsenceManagerWrapper name ';
			amw.label='test AbsenceManagerWrapper label';
			amw.expanded=true;
			amw.disabled=true;
            amw.items=new List<treedata.Items>{itm};   
                  system.assertEquals(amw!=null,true);            
               }
    static testMethod void test_getTreeData(){
    	   List<treedata.AbsenceManagerWrapper> result= treedata.getTreeData();
    		system.assertEquals(result.size(),1);
    }
        static testMethod void test_getAbsencesForApproval(){
    	   List<Absence__c> result= AbsenceController.getAbsencesForApproval();
    		system.assertEquals(result.size(),1);
    }
	
}