force-app/main/default/objects/Absence__c/fields/Approval__c.field-meta.xml
<CustomField>
    <fullName>Approval__c</fullName>
    <label>Approval</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Absence__c/fields/Certificate__c.field-meta.xml
<CustomField>
    <fullName>Certificate__c</fullName>
    <label>Certificate</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No proof required</fullName>
            </value>
            <value>
                <fullName>Proof/medical required</fullName>
            </value>
            <value>
                <fullName>Proof/medical certificate provided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Absence__c/fields/DangerToEmployees__c.field-meta.xml
<CustomField>
    <fullName>DangerToEmployees__c</fullName>
    <label>Danger To Employees</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Absence__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Absence__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Overtime compensation</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Maternity leave</fullName>
            </value>
            <value>
                <fullName>Special leave (paid)</fullName>
            </value>
            <value>
                <fullName>Special leave (unpaid)</fullName>
            </value>
            <value>
                <fullName>disease</fullName>
            </value>
            <value>
                <fullName>No reason</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Absence__c/fields/Workdays__c.field-meta.xml
<CustomField>
    <fullName>Workdays__c</fullName><!-- jours du travail-->
    <label>Workdays</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AbsenceManager__c/AbsenceManager__c.object-meta.xml
<CustomObject>
    <label>Absence Manager</label>
    <nameField>
        <label>Absence Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Absences Manager</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AbsenceController.cls
public with sharing class AbsenceController{
	//absences-for-approval//en attent
@AuraEnabled(cacheable = true)
	public static List<Absence__c> getAbsencesForApproval(){
		List<Absence__c> absences;
		absences = [select ID, Name, absencemanager__r.employee__r.Name, StartDate__c, EndDate__c, Reason__c, Note__c, Certificate__c, Workdays__c,Approval__c
		            from Absence__c
		            where Approval__c = 'Pending'];
		return absences;
	}
 //absencemanager__r.employee__r.Name (relation parent-child) 
 
@AuraEnabled
 public static void updateAbsenceApproval(List<Id> absID){
	List<Absence__c> absToUpdate = new List<Absence__c>();
     for(Id abs : absID){
		for ( Absence__c a : [ 
			select  ID, Name, absencemanager__r.employee__r.Name, StartDate__c, EndDate__c, Reason__c, Note__c, Certificate__c, Workdays__c,Approval__c
			from Absence__c WHERE  ID= :abs]) {
          a.Approval__c  = 'Approved';
          absToUpdate.add(a);
}    }
	if( !absToUpdate.isEmpty() ) {
		update absToUpdate;
	}
   }
 @AuraEnabled(cacheable = true)
	public static List<AbsenceManager__c> getAbsencesManager(){
		List<AbsenceManager__c> absencesManager;
		absencesManager= [select ID, Name, Email__c
		            from AbsenceManager__c
		           ];
		return absencesManager;
	}
@AuraEnabled(cacheable = true)
	public static List<Absence__c> getAbsences(){
		List<Absence__c> absences;
		absences = [select ID, Name, absencemanager__r.employee__r.Name, StartDate__c, EndDate__c, Reason__c, Note__c, Certificate__c, Workdays__c,Approval__c
		            from Absence__c];
		return absences;
	}
@AuraEnabled(cacheable=true)
    public static List<AggregateResult> getAbsenceschart(){
        return [select COUNT(Name) num, Reason__c , Certificate__c FROM Absence__c WHERE  Approval__c ='Approved' AND StartDate__c>=:system.today() AND StartDate__c<=:system.today()+7 GROUP BY Reason__c,Certificate__c];
    }
@AuraEnabled(cacheable=true)
    public static List<AggregateResult> getAbsencescertif(){
        return [select COUNT(Name) num,Reason__c  FROM Absence__c WHERE  Approval__c ='Rejected' AND StartDate__c>=:system.today() AND StartDate__c<=:system.today()+7 GROUP BY Reason__c];
    }


@AuraEnabled(cacheable=true)
public static List<AggregateResult> getabsencepending(){
return [select COUNT(Name) num , Reason__c FROM Absence__c WHERE  Approval__c ='Pending' AND StartDate__c>=:system.today() AND StartDate__c<=:system.today()+7  GROUP BY Reason__c ];
	  

	 

}


@AuraEnabled(cacheable=true)
public static List<AggregateResult> getabsencedanger(){
return [select COUNT(Name) num , DangerToEmployees__c FROM Absence__c WHERE StartDate__c>=:system.today() AND StartDate__c<=:system.today()+7  GROUP BY DangerToEmployees__c];}

@AuraEnabled
public static void rejectAbsenceApproval(List<Id> absID){
	List<Absence__c> absToreject = new List<Absence__c>();
     for(Id abs : absID){
		for ( Absence__c a : [ 
			select  ID, Name, absencemanager__r.employee__r.Name, StartDate__c, EndDate__c, Reason__c, Note__c, Certificate__c, Workdays__c,Approval__c
			from Absence__c WHERE  ID= :abs]) {
          a.Approval__c  = 'Rejected';
          absToreject.add(a);
}    }
	if( !absToreject.isEmpty() ) {
		delete absToreject;
	}
}
@AuraEnabled(cacheable=true)
public static List<AggregateResult> getabsenceManagerrr(){
	return [select COUNT(id) num , Name FROM AbsenceManager__c GROUP BY Name];}
	@AuraEnabled(cacheable=true)
public static List<AbsenceManager__c> getAbsenceManager(){
	return [select ID, Name, Email__c FROM AbsenceManager__c];}

public class relatedFile {
        public String PathOnClient;
        public String Title;
        public Blob VersionData;
    }

    @AuraEnabled
    public static boolean uploadFiles(List<Map<String, Object>> files){
        Boolean isSuccess = false;
        List<ContentVersion> relatedDocuments = new List<ContentVersion>();
        for (Map<String, Object> file : files) {
            String fileJson = JSON.serialize(file);
            relatedFile relatedDocument = (relatedFile) JSON.deserialize(fileJson, relatedFile.class);
            ContentVersion contentVersionFile = new ContentVersion();
            contentVersionFile.PathOnClient = relatedDocument.PathOnClient;
            contentVersionFile.Title = relatedDocument.Title;
            contentVersionFile.VersionData = relatedDocument.VersionData;
            relatedDocuments.add(contentVersionFile);
        }
        Database.saveResult[] srFiles = Database.insert(relatedDocuments);
        for (Database.SaveResult saveResult : srFiles) {
            isSuccess = saveResult.isSuccess();
        }
        return isSuccess;
    }
}